---
- name: Testing andrewrothstein.nerdctl
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'nerdctl --version'
      ansible.builtin.command: /usr/local/bin/nerdctl --version
      changed_when: false
      register: nerdctl_test_output
    - name: Output of 'nerdctl --version'
      ansible.builtin.debug:
        msg: '{{ nerdctl_test_output.stdout }}'
