---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/nerdctl --version
    register: nerdctl_test_output
  - name: nerdctl --version
    debug:
      msg: '{{ nerdctl_test_output.stdout }}'
