---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ nerdctl_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ nerdctl_install_dir }}'
  changed_when: false
  register: nerdctl_binary
- name: Downloading and installing nerdctl
  when: not nerdctl_binary.stat.exists
  block:
    - name: Downloading {{ nerdctl_url }} to {{ nerdctl_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ nerdctl_url }}'
        dest: '{{ nerdctl_tmp_archive }}'
        mode: '644'
        checksum: '{{ nerdctl_checksum }}'
    - name: Mkdir {{ nerdctl_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ nerdctl_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchiving {{ nerdctl_tmp_archive }} to {{ nerdctl_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ nerdctl_tmp_archive }}'
        dest: '{{ nerdctl_install_dir }}'
        creates: '{{ nerdctl_install_exe }}'
  always:
    - name: Rm {{ nerdctl_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ nerdctl_tmp_archive }}'
        state: absent
- name: Linking {{ nerdctl_link }} to {{ nerdctl_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ nerdctl_install_exe }}'
    dest: '{{ nerdctl_link }}'
    state: link
